---
- hosts: production
  become_user: root
  tasks:
  - name: Install apache2 on ubuntu servers
    apt: name=apache2 state=present update_cache=yes
    when: ansible_distribution == "Ubuntu"

  - name: install httpd on CentOS
    yum: name=httpd state=latest
    when: ansible_distribution == "CentOS"

  - name: Deploy index.html
    copy: src=/root/playbooks/index.html dest=/var/www/html/index.html

  - name: start apache2 on ubuntu
    service: name=apache2 state=restarted
    when: ansible_distribution == "Ubuntu"
         
  - name: start httpd on centos
    service: name=httpd state=restarted
    when: ansible_distribution == "CentOS"
